name: perfect_freehand
version: 1.0.3
description: Draw perfect pressure-sensitive freehand lines. A set of functions for turning input points into a polygon of outline points.
homepage: https://github.com/steveruizok/perfect-freehand-dart
repository: https://github.com/steveruizok/perfect-freehand-dart
documentation: https://github.com/steveruizok/perfect-freehand-dart
issue_tracker: https://github.com/steveruizok/perfect-freehand-dart/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
